# Generated by Django 3.0.4 on 2020-03-16 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nom')),
                ('surname', models.CharField(max_length=25, verbose_name='Prénom')),
                ('photo', models.URLField(blank=True, verbose_name='Photo')),
                ('birthDate', models.DateField(blank=True, verbose_name='Date de naissance')),
                ('deathDate', models.DateField(blank=True, verbose_name='Date de décès')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du livre')),
                ('available', models.BooleanField(default=True, verbose_name='Disponneble ?')),
                ('parution', models.DateField(verbose_name='Date de parution')),
                ('nbPages', models.PositiveIntegerField(verbose_name='Nombre de pages')),
                ('nature', models.CharField(max_length=200, verbose_name='Nature du livre')),
                ('couverture', models.URLField(blank=True, verbose_name='Image de courverture')),
                ('resume', models.TextField(verbose_name='Résumé')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIOSQUE.Auteur')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('photo', models.URLField(blank=True, verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Editeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('website', models.URLField(blank=True, verbose_name='Site internet')),
                ('phone', models.CharField(blank=True, max_length=13, verbose_name='Téléphone')),
                ('adresse', models.CharField(blank=True, max_length=200, verbose_name='Adresse')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reserved', models.BooleanField(default=False, verbose_name='Réservé ?')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='KIOSQUE.Book')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KIOSQUE.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='editeur',
            field=models.ManyToManyField(related_name='books', to='KIOSQUE.Editeur'),
        ),
    ]
